spring.application.name=reco
#Conectar mysql
#spring.datasource.url=jdbc:mysql://localhost:3306/reco?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=root1234
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#Conectar a neon
spring.datasource.url=jdbc:postgresql://ep-bold-star-at03twd2-pooler.c-9.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_e3CIjWRw2isd&sslmode=require&channelBinding=require
spring.datasource.username=ethanKabalzt
spring.datasource.password=npg_e3CIjWRw2isd
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect